const matSol = require("./matrix0");
const isOneChangSol = require("./isOneChange");
const isPermutationOfPalindrome = require("./isPermutationOfPalindrome");
const removeDupSol = require("./removeDup");
const sumLinkedList = require("./sumLinkedList");
const minStack = require("./MinStack");
const largestComponent = require("./largestComponentInGraph");
const minimalIsland = require("./minimalIsland");
const shortestPath = require("./shortestPath");
const sparseSearch = require("./sparseSearch.js");
const specialQueue = require("./queueViaStack");
const listOfDepth = require("./listOfDepth");
const isBalanced = require("./isBalanced");

matSol();
isOneChangSol();
isPermutationOfPalindrome();
removeDupSol();
sumLinkedList();
minStack();
largestComponent();
minimalIsland();
shortestPath();
sparseSearch();
specialQueue();
listOfDepth();
isBalanced();
